services:
  notifs:
    build:
      context: .
      dockerfile: notifs.Dockerfile
    container_name: seatsteal-notifs
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./:/app

  scraper:
    build:
      context: .
      dockerfile: scraper.Dockerfile
    container_name: seatsteal-scraper
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./:/app
